message_types:
  D: NewOrderSingle
  F: OrderCancelRequest
  G: OrderCancelReplaceRequest
  H: OrderStatusRequest
  J: Allocation
  K: ListCancelRequest
  L: ListExecute
  N: ListStatusRequest
  P: AllocationACK
  Q: DontKnowTrade
  R: QuoteRequest
  S: Quote
  T: SettlementInstructions
  V: MarketDataRequest
  W: MarketDataSnapshotFullRefresh
  X: MarketDataIncrementalRefresh
  Y: MarketDataRequestReject
  Z: QuoteCancel
  a: QuoteStatusRequest
  b: MassQuoteAcknowledgement
  c: SecurityDefinitionRequest
  d: SecurityDefinition
  e: SecurityStatusRequest
  f: SecurityStatus
  g: TradingSessionStatusRequest
  h: TradingSessionStatus
  i: MassQuote
  j: BusinessMessageReject
  k: BidRequest
  l: BidResponse
  m: ListStrikePrice
  n: XMLnonFIX
  o: RegistrationInstructions
  p: RegistrationInstructionsResponse
  q: OrderMassCancelRequest
  r: OrderMassCancelReport
  s: NewOrderCross
  t: CrossOrderCancelReplaceRequest
  u: CrossOrderCancelRequest
  v: SecurityTypeRequest
  w: SecurityTypes
  x: SecurityListRequest
  y: SecurityList
  z: DerivativeSecurityListRequest
  AA: DerivativeSecurityList
  AB: NewOrderMultileg
  AC: MultilegOrderCancelReplaceRequest
  AD: TradeCaptureReportRequest
  AE: TradeCaptureReport
  AF: OrderMassStatusRequest
  AG: QuoteRequestReject
  AH: RFQRequest
  AI: QuoteStatusReport
  AJ: QuoteResponse
  AK: Confirmation
  AL: PositionMaintenanceRequest
  AM: PositionMaintenanceReport
  AN: RequestForPositions
  AO: RequestForPositionsAck
  AP: PositionReport
  AQ: TradeCaptureReportRequestAck
  AR: TradeCaptureReportAck
  AS: AllocationReport
  AT: AllocationReportAck
  AU: ConfirmationAck
  AV: SettlementInstructionRequest
  AW: AssignmentReport
  AX: CollateralRequest
  AY: CollateralAssignment
  AZ: CollateralResponse
  BA: CollateralReport
  BB: CollateralInquiry
  BC: NetworkStatusRequest
  BD: NetworkStatusResponse
  BE: UserRequest
  BF: UserResponse
  BG: CollateralInquiryAck
  BH: ConfirmationRequest
  BI: TradingSessionListRequest
  BJ: TradingSessionList
  BK: SecurityListUpdateReport
  BL: AdjustedPositionReport
  BM: AllocationInstructionAlert
  BN: ExecutionAcknowledgement
  BO: ContraryIntentionReport
  BP: SecurityDefinitionUpdateReport 